export const theme = {
  colors: {
    primary: "#7C6FE0",
    secondary: "#4ECDC4",
    accent: "#FF6B6B",
    user: "#00BCD4",
    assistant: "#66BB6A",
    dim: "#666666",
    dimLight: "#888888",
    border: "#444444",
    borderLight: "#555555",
    success: "#66BB6A",
    warning: "#FFA726",
    error: "#EF5350",
    muted: "#9E9E9E",
    banner: [
      "#afd7ff",
      "#87d7ff",
      "#87afff",
      "#8787d7",
      "#d7afff",
      "#d787d7",
      "#ffd7ff",
      "#d75fd7",
    ],
  },
  symbols: {
    dot: "●",
    dotEmpty: "○",
    separator: "─",
    borderTop: "▀",
    borderBottom: "▄",
    chevron: "❯",
    arrow: "▸",
    diamond: "◇",
    sparkle: "✧",
    check: "✓",
    cross: "✗",
    ellipsis: "…",
  },
  sparkleFrames: [
    " ·  ",
    "  ✧ ",
    "   ·",
    "  ✧ ",
    " · ✧",
    "  · ✧",
    " ✧ · ",
    "  ✧  ",
  ],
} as const;
